name: geko_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - astropy
  - matplotlib
  - scipy
  - astropy::reproject
  - arviz
  - photutils
  - pip
  - pytest
  - pip:
      - corner==2.2.3
      - jax==0.6.1
      - jaxlib==0.6.1
      - numpyro==0.18.0
