name: CI with Conda

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11.0  # or your desired python version
        environment-file: environment.yml
        activate-environment: geko_env
        use-mamba: true

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q
