name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: geko_env
        python-version: 3.11  # You can omit this if already in environment.yml
        use-mamba: true
        auto-update-conda: true

    - name: Install pip dependencies
      shell: bash -l {0}  # ensure environment is loaded
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Debug environment
      shell: bash -l {0}
      run: |
        which python
        python --version
        which pytest
        pytest --version

    - name: Run tests with pytest
      shell: bash -l {0}
      run: |
        cd ..
        pytest --maxfail=1 --disable-warnings -q
